### ISSUE TITLE
Can you lend me a helping hand?

### ISSUE THREAD

**Issue by FurryColtin** [Starmapo/FNF-PsychEngine-Extra#1]
### What is your question?

Hey i want a lil helping hand on some coding for psych engine but better will credit if you do! also i wanna help with this too!

**Comment by Starmapo** [comment]
I'm not interested in helping anyone out right now, but you are always free to make pull requests, this repository will be public.
You can just take code from here if you want honestly, i did the same with other engines anyways.

**Comment by FurryColtin** [comment]
> I'm not interested in helping anyone out right now, but you are always free to make pull requests, this repository will be public. You can just take code from here if you want honestly, i did the same with other engines anyways.

ok. ive move on from that because some people were being mean :c but ill try to help you as much as possible!
