### ISSUE TITLE
an input issue to 7k and above

### ISSUE THREAD

**Issue by Meliach** [Starmapo/FNF-PsychEngine-Extra#4]
### Describe your bug here.

Only occurs when playing 7+ keys.
When pressing multiple keys, some of the rest of the keys won't register at all.
(I pressed around 7 keys at once but only registered around 4 or 3, etc.)

You can see the problem if you press all the keys at once.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by prokube** [comment]
that's a keyboard issue. [check a keyboard ghosting test](https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo)

**Comment by Starmapo** [comment]
> that's a keyboard issue. [check a keyboard ghosting test](https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo)

I can confirm my keyboard does the same thing. Only a hardware problem

**Comment by Meliach** [comment]
> that's a keyboard issue. [check a keyboard ghosting test](https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo)

just checked, and it actually is a keyboard issue
