### ISSUE TITLE
Problem with miss animations

### ISSUE THREAD

**Issue by Meliach** [Starmapo/FNF-PsychEngine-Extra#5]
### Describe your bug here.

Forgot to mention this, so basically the miss animations will stay forever until you hit a note.
I dunno if this is intentional.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by Starmapo** [comment]
Should be fixed now
