### ISSUE TITLE
Change Character Event crashes

### ISSUE THREAD

**Issue by BeastlyGhost** [Starmapo/FNF-PsychEngine-Extra#7]
### Describe your bug here.

https://user-images.githubusercontent.com/45212377/159109226-43366656-3751-4640-b8bd-e6411af3afc0.mp4

![image](https://user-images.githubusercontent.com/45212377/159109233-79d99e14-82aa-473a-8fbd-03fa51dd8f27.png)
this character does exist

and it happens even with vanilla characters

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing on source or lua, just added the event

**Comment by Starmapo** [comment]
Fixed with latest commit
