### ISSUE TITLE
Compiling problem after the latest commit

### ISSUE THREAD

**Issue by Meliach** [Starmapo/FNF-PsychEngine-Extra#8]
### Describe your bug here.

hmm idk where did this thing come from
I haven't tried to remove this code since it might ruin something

### Command Prompt/Terminal logs (if existing)

```bash
source/flixel/FlxSprite.hx:24: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
source/flixel/FlxSprite.hx:125: characters 34-51 : Type not found : FlxDirectionFlags
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah.

**Comment by Starmapo** [comment]
Do you have the latest Haxe installed? The FlxSprite code is from 4.11.0 and FlxDirectionFlags was added in 4.10.0.

**Comment by Meliach** [comment]
hmmmm I think I haven't checked about it, let me check

**Comment by Meliach** [comment]
So my Flixel is actually outdated and I updated it to 4.11.0.
The source finally compiles now so thank you.
